import { Kysely } from 'kysely';
import { XataDialect, type Model } from '@xata.io/kysely';
import { type DatabaseSchema, getXataClient } from '../xata'; // Generated by Xata CLI

// Initialize the Xata client
const xata = getXataClient();

// Set up Kysely with the Xata dialect
const db = new Kysely<Model<DatabaseSchema>>({
  dialect: new XataDialect({ xata }),
});

export { db };